apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-certmanager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=false
  project: default
  destination:
    name: kind-test-1
    namespace: cert-manager
  sources:
    - repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: shared/jit-rbac-roles
      directory:
        include: certmanager-role.yaml
    - repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: shared/jit-rbac
      kustomize:
        commonLabels:
          jit-rbac/app: k8s-spb2-backend1-certmanager
        patches:
          - target:
              kind: Job
              name: argocd-jit-rbac-ensure-empty-role
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/env/1/value
                value: argocd-manager-certmanager
          - target:
              kind: Job
              name: argocd-jit-rbac-enrich-role
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/env/1/value
                value: argocd-manager-certmanager
              - op: replace
                path: /spec/template/spec/containers/0/env/2/value
                value: jit-rbac-certmanager-rules
          - target:
              kind: Job
              name: argocd-jit-rbac-clear-role
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/env/1/value
                value: argocd-manager-certmanager
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: cert-manager
      helm:
        releaseName: k8s-spb2-backend1-certmanager
        values: |
          installCRDs: true