apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-certmanager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    jit-rbac/required-role: "argocd-manager-certmanager"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=false
  project: default
  destination:
    name: kind-test-1
    namespace: cert-manager
  sources:
    - repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: shared/jit-rbac-certmanager
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: cert-manager
      helm:
        releaseName: k8s-spb2-backend1-certmanager
        values: |
          installCRDs: true