apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-coredns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - FailOnSharedResource=false
  project: default
  destination:
    namespace: kube-system
    name: k8s-spb2-backend1
  sources:
    # JIT RBAC hooks (PreSync + PostSync)
    - repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: shared/jit-rbac
      kustomize:
        commonLabels:
          jit-rbac/app: k8s-spb2-backend1-coredns
        patches:
          - target:
              kind: ClusterRole
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-coredns
          - target:
              kind: ClusterRoleBinding
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-coredns
              - op: replace
                path: /roleRef/name
                value: argocd-manager-coredns
          - target:
              kind: CronJob
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend1-coredns-cleanup-cron
          - target:
              kind: Job
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend1-coredns-cleanup
    # JIT RBAC role definition
    - repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: shared/jit-rbac-roles
      directory:
        include: coredns-role.yaml
    # CoreDNS Helm chart
    - repoURL: 'https://artifactory.playteam.ru:443/artifactory/helm/'
      targetRevision: 1.12.1-okko-v1
      chart: coredns
      helm:
        releaseName: coredns
        valuesObject:
          #Values
          image:
            repository: registry.playteam.ru/kubernetes/coredns
            tag: 1.12.1
            pullPolicy: IfNotPresent
          replicas: 8
          tolerations:
            - key: node-role.kubernetes.io/infr
              operator: Exists
              effect: NoSchedule
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/infr
                        operator: Exists