apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-jit-rbac-roles
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=false
  project: default
  destination:
    name: kind-test-1
    namespace: kube-system
  source:
    repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
    targetRevision: HEAD
    path: shared/jit-rbac-roles
    directory:
      recurse: true