apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=true
    - ServerSideApply=true
    automated:
      prune: false
      selfHeal: false
  project: default
  destination:
    name: kind-test-1
    namespace: keda
  sources:
    - repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: shared/jit-rbac
      kustomize:
        commonLabels:
          jit-rbac/app: k8s-spb2-backend1-keda
        patches:
          - target:
              kind: ClusterRole
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-keda
          - target:
              kind: ClusterRoleBinding
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-keda
              - op: replace
                path: /roleRef/name
                value: argocd-manager-keda
          - target:
              kind: CronJob
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend1-keda-cleanup-cron
          - target:
              kind: Job
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend1-keda-cleanup
    - repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: shared/jit-rbac-roles
      directory:
        include: keda-role.yaml
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: keda
      helm:
        releaseName: k8s-spb2-backend1-keda
        valuesObject:
          #values.yaml
          image:
            keda:
              repository: ghcr.io/kedacore
              # Allows people to override tag if they don't want to use the app version
              tag: 2.16.1
            metricsApiServer:
              repository: ghcr.io/kedacore/keda-metrics-apiserver
              # Allows people to override tag if they don't want to use the app version
              tag: 2.16.1
          webhooks:
            enabled: false
            certManager:
              enabled: false
            generateCertificates: false
          operator:
            tls:
              enabled: false
          crds:
            install: true
          tolerations:
          - key: "node-role.kubernetes.io/infr"
            operator: "Exists"
            effect: "NoSchedule"
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                    - key: "node-role.kubernetes.io/infr"
                      operator: "Exists"
