apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-screenapi-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: batch
    kind: Job
  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - RespectIgnoreDifferences=true
    - CreateNamespace=false
    - FailOnSharedResource=false
  project: default
  destination:
    name: kind-test-1
    namespace: kube-system
  sources:
    - repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: shared/jit-rbac
      kustomize:
        commonLabels:
          jit-rbac/app: k8s-spb2-backend1-screenapi-nginx
        patches:
          - target:
              kind: ClusterRole
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-screenapi-nginx
          - target:
              kind: ClusterRoleBinding
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-screenapi-nginx
              - op: replace
                path: /roleRef/name
                value: argocd-manager-screenapi-nginx
          - target:
              kind: CronJob
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend1-screenapi-nginx-cleanup-cron
          - target:
              kind: Job
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend1-screenapi-nginx-cleanup
    - repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: shared/jit-rbac-roles
      directory:
        include: screenapi-nginx-role.yaml
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: kubernetes-ingress
      helm:
        releaseName: screenapi-ingress-nginx
        values: |
          controller:
            image:
              repository: haproxytech/kubernetes-ingress
            replicaCount: 2
          defaultBackend:
            image:
              repository: registry.k8s.io/defaultbackend-amd64
              tag: 1.5
