apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-policy-reporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=true
    - ServerSideApply=true
    automated:
      prune: false
      selfHeal: false
  project: default
  destination:
    name: kind-test-1
    namespace: kyverno
  sources:
    - repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: shared/jit-rbac
      kustomize:
        commonLabels:
          jit-rbac/app: k8s-spb2-backend1-policy-reporter
        patches:
          - target:
              kind: ClusterRole
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-policy-reporter
          - target:
              kind: ClusterRoleBinding
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-policy-reporter
              - op: replace
                path: /roleRef/name
                value: argocd-manager-policy-reporter
          - target:
              kind: CronJob
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend1-policy-reporter-cleanup-cron
          - target:
              kind: Job
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend1-policy-reporter-cleanup
    - repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: shared/jit-rbac-roles
      directory:
        include: policy-reporter-role.yaml
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: policy-reporter
      helm:
        releaseName: policy-reporter
        values: |
          image:
            registry: ghcr.io
            repository: kyverno/policy-reporter
            tag: 2.24.1
          logging:
            encoding: json
          monitoring:
            enabled: true
          resources:
            limits:
              memory: 512Mi
              cpu: 1
            requests:
              memory: 75Mi
              cpu: 5m
          tolerations:
            - key: "node-role.kubernetes.io/infr"
              operator: "Exists"
              effect: "NoSchedule"
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                      - key: "node-role.kubernetes.io/infr"
                        operator: "Exists"
