apiVersion: batch/v1
kind: Job
metadata:
  generateName: argocd-jit-rbac-cleanup-
  namespace: kube-system
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
    argocd.argoproj.io/sync-wave: "99"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argo-jit-rbac
    spec:
      serviceAccountName: argocd-manager
      restartPolicy: Never
      containers:
      - name: cleanup
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-lc"]
        args:
          - |
            echo "Deleting temporary CRB for app $ARGOCD_APP_NAME";
            kubectl delete clusterrolebinding -l jit-rbac-app=$ARGOCD_APP_NAME --ignore-not-found=true;
            echo "Done";