apiVersion: batch/v1
kind: Job
metadata:
  generateName: argocd-jit-rbac-cleanup-
  namespace: kube-system
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
    argocd.argoproj.io/sync-wave: "99"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argo-jit-rbac
    spec:
      serviceAccountName: argocd-manager
      restartPolicy: Never
      containers:
      - name: cleanup
        image: bitnami/kubectl:1.30
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-lc"]
        args:
          - |
            echo "Deleting temporary CRBs with label app.kubernetes.io/part-of=argo-jit-rbac";
            kubectl delete clusterrolebinding -l app.kubernetes.io/part-of=argo-jit-rbac --ignore-not-found=true;
            echo "Deleting ephemeral ClusterRole argocd-manager-full (if present)";
            kubectl delete clusterrole argocd-manager-full --ignore-not-found=true;
            echo "Done";

