apiVersion: batch/v1
kind: CronJob
metadata:
  name: APP_NAME_PLACEHOLDER-cleanup-cron
  namespace: kube-system
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: APP_NAME_PLACEHOLDER
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  suspend: false
  startingDeadlineSeconds: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
            app.kubernetes.io/part-of: argo-jit-rbac
            jit-rbac/app: APP_NAME_PLACEHOLDER
        spec:
          serviceAccountName: argocd-manager
          restartPolicy: Never
          containers:
          - name: cleanup
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args:
              - |
                set -euo pipefail
                echo "Starting cleanup at $(date -u +%FT%TZ)";
                
                PENDING_PODS=$(kubectl get pods -n kube-system -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} \
                  --field-selector=status.phase=Pending -o jsonpath='{.items[*].metadata.name}' 2>/dev/null || echo "");
                RUNNING_PODS=$(kubectl get pods -n kube-system -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} \
                  --field-selector=status.phase=Running -o jsonpath='{.items[*].metadata.name}' 2>/dev/null || echo "");
                UNKNOWN_PODS=$(kubectl get pods -n kube-system -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} \
                  --field-selector=status.phase=Unknown -o jsonpath='{.items[*].metadata.name}' 2>/dev/null || echo "");
                
                ACTIVE_PODS="${PENDING_PODS} ${RUNNING_PODS} ${UNKNOWN_PODS}"
                ACTIVE_PODS=$(echo "${ACTIVE_PODS}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
                
                if [ -n "${ACTIVE_PODS}" ]; then
                  echo "Found active pods for ${JIT_RBAC_APP}: ${ACTIVE_PODS}, skipping cleanup to avoid interrupting sync";
                  exit 0;
                fi

                kubectl delete pod -n kube-system -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} --field-selector=status.phase=Succeeded --ignore-not-found=true || true;
                
                echo "Cleanup completed at $(date -u +%FT%TZ)";
            env:
            - name: JIT_RBAC_APP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['jit-rbac/app']