apiVersion: batch/v1
kind: Job
metadata:
  name: APP_NAME_PLACEHOLDER-wait
  namespace: kube-system
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: APP_NAME_PLACEHOLDER
    jit-rbac/type: wait
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argo-jit-rbac
        jit-rbac/app: APP_NAME_PLACEHOLDER
    spec:
      serviceAccountName: argocd-manager
      restartPolicy: Never
      containers:
      - name: wait
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ROLE_NAME
          value: "ROLE_NAME_PLACEHOLDER"
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -euo pipefail
            echo "Starting RBAC propagation wait at $(date -u +%FT%TZ)"
            
            # Ждём 5 секунд для RBAC propagation
            echo "Waiting 5 seconds for RBAC propagation..."
            sleep 5
            
            # Проверяем, что ClusterRole заполнен правилами
            echo "Verifying ClusterRole ${ROLE_NAME} has rules..."
            
            RULES=$(kubectl get clusterrole "${ROLE_NAME}" -o jsonpath='{.rules}' 2>/dev/null || echo "[]")
            
            if [ "${RULES}" = "[]" ] || [ -z "${RULES}" ]; then
              echo "⚠ WARNING: ClusterRole ${ROLE_NAME} has no rules!"
              exit 1
            else
              echo "✓ ClusterRole ${ROLE_NAME} has rules populated"
              kubectl get clusterrole "${ROLE_NAME}" -o jsonpath='{.rules[*].resources}' | head -c 100
              echo "..."
            fi
            
            # Дополнительная пауза для полной propagation
            echo "Additional 2 seconds for propagation..."
            sleep 2
            
            echo "RBAC propagation completed at $(date -u +%FT%TZ)"