apiVersion: batch/v1
kind: CronJob
metadata:
  name: APP_NAME_PLACEHOLDER-cleanup-cron
  namespace: kube-system
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: APP_NAME_PLACEHOLDER
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  suspend: true
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
            app.kubernetes.io/part-of: argo-jit-rbac
            jit-rbac/app: APP_NAME_PLACEHOLDER
        spec:
          serviceAccountName: argocd-manager
          restartPolicy: Never
          containers:
          - name: cleanup
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args:
              - |
                echo "Starting cleanup at $(date)";
                CRB_EXISTS=$(kubectl get clusterrolebinding -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} -o name 2>/dev/null || echo "");
                if [ -z "${CRB_EXISTS}" ]; then
                  echo "No JIT-RBAC ClusterRoleBinding for ${JIT_RBAC_APP}; skipping cleanup";
                  exit 0;
                fi
                AGE_THRESHOLD_MIN=${AGE_THRESHOLD_MIN:-15}
                CRB_NAME=$(kubectl get clusterrolebinding -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "");
                CRB_CT=$(kubectl get clusterrolebinding "${CRB_NAME}" -o jsonpath='{.metadata.creationTimestamp}' 2>/dev/null || echo "");
                if [ -z "${CRB_CT}" ]; then
                  echo "Cannot determine CRB creation time; skipping cleanup";
                  exit 0;
                fi
                now_epoch=$(date -u +%s)
                crb_epoch=$(date -u -d "${CRB_CT}" +%s 2>/dev/null || echo 0)
                if [ "${crb_epoch}" = "0" ]; then
                  echo "Failed to parse CRB creation time; skipping cleanup";
                  exit 0;
                fi
                age_min=$(( (now_epoch - crb_epoch) / 60 ))
                if [ ${age_min} -lt ${AGE_THRESHOLD_MIN} ]; then
                  echo "CRB '${CRB_NAME}' age ${age_min}m < threshold ${AGE_THRESHOLD_MIN}m; skipping cleanup";
                  exit 0;
                fi
                kubectl delete pod -n kube-system -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} --field-selector=status.phase=Succeeded --ignore-not-found=true || true;
                echo "Cleanup completed at $(date)";
            env:
            - name: JIT_RBAC_APP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['jit-rbac/app']