apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  generateName: argocd-manager-full-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookFailed,HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-manager-full
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system
