apiVersion: batch/v1
kind: Job
metadata:
  name: APP_NAME_PLACEHOLDER-pre-cleanup
  namespace: kube-system
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: APP_NAME_PLACEHOLDER
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argo-jit-rbac
        jit-rbac/app: APP_NAME_PLACEHOLDER
    spec:
      serviceAccountName: argocd-manager
      restartPolicy: Never
      containers:
      - name: cleanup
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -euo pipefail
            echo "Starting PreSync cleanup for ${JIT_RBAC_APP} at $(date -u +%FT%TZ)";
            
            CRB_EXISTS=$(kubectl get clusterrolebinding -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} -o name 2>/dev/null || echo "");
            if [ -z "${CRB_EXISTS}" ]; then
              exit 0;
            fi
            
            CRB_NAME=$(kubectl get clusterrolebinding -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "");
            ROLE_NAME=$(kubectl get clusterrolebinding -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} -o jsonpath='{.items[0].roleRef.name}' 2>/dev/null || echo "");
            
            kubectl delete pod -n kube-system -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} --field-selector=status.phase=Succeeded --ignore-not-found=true || true;
            
            if [ -n "${CRB_NAME}" ]; then
              kubectl patch clusterrolebinding "${CRB_NAME}" --type=merge -p '{"metadata":{"finalizers":[]}}' --ignore-not-found=true || true;
              kubectl delete clusterrolebinding "${CRB_NAME}" --ignore-not-found=true || true;
            fi
            
            if [ -n "${ROLE_NAME}" ] && [ "${ROLE_NAME}" != "argocd-manager-watcher" ]; then
              kubectl patch clusterrole "${ROLE_NAME}" --type=merge -p '{"rules": []}' --ignore-not-found=true || true;
            fi
            
            echo "PreSync cleanup completed for ${JIT_RBAC_APP} at $(date -u +%FT%TZ)";
        env:
        - name: JIT_RBAC_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['jit-rbac/app']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ROLE_NAME_PLACEHOLDER
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: APP_NAME_PLACEHOLDER
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ROLE_NAME_PLACEHOLDER
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: APP_NAME_PLACEHOLDER
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ROLE_NAME_PLACEHOLDER
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system