apiVersion: batch/v1
kind: Job
metadata:
  name: APP_NAME_PLACEHOLDER-wait
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: APP_NAME_PLACEHOLDER
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argo-jit-rbac
        jit-rbac/app: APP_NAME_PLACEHOLDER
    spec:
      serviceAccountName: argocd-manager
      restartPolicy: Never
      containers:
      - name: wait
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Waiting 3 seconds for RBAC propagation at $(date -u +%FT%TZ)"
            sleep 3
            echo "Wait completed at $(date -u +%FT%TZ)"