# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: cleanup-old-rbac
#   namespace: kube-system
#   annotations:
#     argocd.argoproj.io/hook: PreSync
#     argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
#     argocd.argoproj.io/sync-wave: "-4"
#   labels:
#     app.kubernetes.io/part-of: argo-jit-rbac
#     jit-rbac/global-cleanup: "true"
# spec:
#   backoffLimit: 0
#   ttlSecondsAfterFinished: 60
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/part-of: argo-jit-rbac
#     spec:
#       serviceAccountName: argocd-manager
#       restartPolicy: Never
#       containers:
#       - name: cleanup-old-rbac
#         image: bitnami/kubectl:latest
#         imagePullPolicy: IfNotPresent
#         command: ["/bin/sh", "-c"]
#         args:
#           - |
#             set -u
#             echo "Starting cleanup of old RBAC resources at $(date -u +%FT%TZ)";
#             kubectl delete clusterrolebinding argocd-manager-role-binding --ignore-not-found=true 2>/dev/null || true;
#             kubectl delete clusterrole argocd-manager-role --ignore-not-found=true 2>/dev/null || true;
#             echo "Cleanup of old RBAC resources completed at $(date -u +%FT%TZ)";
# ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ROLE_NAME_PLACEHOLDER
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: APP_NAME_PLACEHOLDER
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ROLE_NAME_PLACEHOLDER-install
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: APP_NAME_PLACEHOLDER
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ROLE_NAME_PLACEHOLDER
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: APP_NAME_PLACEHOLDER-cleanup-cron
  namespace: kube-system
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: APP_NAME_PLACEHOLDER
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
            app.kubernetes.io/part-of: argo-jit-rbac
            jit-rbac/app: APP_NAME_PLACEHOLDER
        spec:
          serviceAccountName: argocd-manager
          restartPolicy: Never
          containers:
          - name: cleanup
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/bash", "-c"]
            args:
              - |
                set -euo pipefail
                echo "Starting cleanup at $(date -u +%FT%TZ)"
                echo "Cleaning up succeeded pods for app: ${JIT_RBAC_APP}"
                kubectl delete pod -n kube-system -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} --field-selector=status.phase=Succeeded --ignore-not-found=true || true
                echo "Cleanup completed at $(date -u +%FT%TZ)"
            env:
            - name: JIT_RBAC_APP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['jit-rbac/app']