apiVersion: batch/v1
kind: CronJob
metadata:
  name: APP_NAME_PLACEHOLDER-cleanup-cron
  namespace: kube-system
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: APP_NAME_PLACEHOLDER
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  suspend: false
  startingDeadlineSeconds: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
            app.kubernetes.io/part-of: argo-jit-rbac
            jit-rbac/app: APP_NAME_PLACEHOLDER
        spec:
          serviceAccountName: argocd-manager
          restartPolicy: Never
          containers:
          - name: cleanup
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args:
              - |
                set -euo pipefail
                echo "Starting per-app cleanup for ${JIT_RBAC_APP} at $(date -u +%FT%TZ)";
                
                AGE_THRESHOLD_MIN=${AGE_THRESHOLD_MIN:-3}
                now_epoch=$(date -u +%s)
                
                CRB_INFO=$(kubectl get clusterrolebinding -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} \
                  -o jsonpath='{.items[0].metadata.name}{"\t"}{.items[0].metadata.creationTimestamp}{"\n"}' 2>/dev/null || echo "");
                
                if [ -n "${CRB_INFO}" ]; then
                  IFS=$'\t' read -r crb_name crb_ct <<< "${CRB_INFO}"
                  crb_epoch=$(date -u -d "${crb_ct}" +%s 2>/dev/null || echo 0)
                  
                  if [ "${crb_epoch}" != "0" ]; then
                    age_min=$(( (now_epoch - crb_epoch) / 60 ))
                    if [ ${age_min} -lt ${AGE_THRESHOLD_MIN} ]; then
                      echo "ClusterRoleBinding '${crb_name}' is only ${age_min} minute(s) old, skipping cleanup (threshold: ${AGE_THRESHOLD_MIN} min)";
                      exit 0;
                    fi
                  fi
                else
                  echo "No ClusterRoleBinding found for ${JIT_RBAC_APP}, proceeding with safe pod cleanup only";
                fi
                
                timeout 30 kubectl delete pod -n kube-system -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/app=${JIT_RBAC_APP} \
                  --field-selector=status.phase=Succeeded --ignore-not-found=true --force --grace-period=0 || true;
                
                echo "Per-app cleanup completed for ${JIT_RBAC_APP} at $(date -u +%FT%TZ)";
            env:
            - name: JIT_RBAC_APP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['jit-rbac/app']