apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-watcher
rules:
  - apiGroups: ["admissionregistration.k8s.io", "apiextensions.k8s.io", "apiregistration.k8s.io", "apps", "autoscaling.k8s.io", "autoscaling", "batch", "cert-manager.io", "extensions", "flowcontrol.apiserver.k8s.io", "grafana.integreatly.org", "jaegertracing.io", "keda.sh", "monitoring.coreos.com", "networking.k8s.io", "operator.victoriametrics.com", "policy", "rbac.authorization.k8s.io", "ricoberger.de", "", "velero.io", "storage.k8s.io"]
    resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
    - apiservices
    - daemonsets
    - deployments
    - statefulsets
    - verticalpodautoscalers
    - horizontalpodautoscalers
    - cronjobs
    - certificates
    - issuers
    - ingresses
    - flowschemas
    - prioritylevelconfigurations
    - grafanadashboards
    - jaegers
    - scaledobjects
    - podmonitors
    - prometheusrules
    - servicemonitors
    - ingressclasses
    - networkpolicies
    - vmagents
    - vmnodescrapes
    - vmpodscrapes
    - vmservicescrapes
    - poddisruptionbudgets
    - podsecuritypolicies
    - clusterrolebindings
    - clusterroles
    - rolebindings
    - roles
    - vaultsecrets
    - configmaps
    - endpoints
    - namespaces
    - pods
    - secrets
    - serviceaccounts
    - services
    - backupstoragelocations
    - schedules
    - volumesnapshotlocations
    - persistentvolumeclaims
    - persistentvolumes
    - storageclasses
    - csistoragecapacities
    verbs: ["get", "list", "watch"]
  # - apiGroups: ["apiextensions.k8s.io"]
  #   resources: ["customresourcedefinitions"]
  #   verbs: ["get", "list", "watch"]
  # - apiGroups: [""]
  #   resources: ["events"]
  #   verbs: ["create", "list"]
  # - apiGroups: [""]
  #   resources: ["namespaces"]
  #   verbs: ["create"]
  # - apiGroups: ["rbac.authorization.k8s.io"]
  #   resources: ["clusterrolebindings"]
  #   verbs: ["create", "delete"]
  # - apiGroups: ["rbac.authorization.k8s.io"]
  #   resources: ["clusterroles"]
  #   resourceNames: ["argocd-manager-full", "argocd-manager-certmanager"]
  #   verbs: ["bind", "get", "update", "patch"]
  # - apiGroups: ["rbac.authorization.k8s.io"]
  #   resources: ["clusterroles"]
  #   verbs: ["create","escalate"]
  # - apiGroups: ["batch"]
  #   resources: ["jobs"]
  #   verbs: ["delete", "list", "get", "watch", "update"]