apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-certmanager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - CreateNamespace=true
  project: k8s-spb2-backend1
  destination:
    server: https://spoke-1-control-plane:6443
    namespace: cert-manager
  source:
    repoURL: 'https://github.com/nomad-mrkn/charts.git'
    targetRevision: HEAD
    path: cert-manager
    helm:
      values: |
        installCRDs: true