apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=false
  project: kind-spoke-1
  destination:
    name: kind-spoke-1
    namespace: cert-manager
  source:
    repoURL: 'https://github.com/nomad-mrkn/charts.git'
    targetRevision: HEAD
    path: cert-manager
    helm:
      values: |
        installCRDs: true
