# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: k8s-spb2-backend1-certmanager
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"
# spec:
#   syncPolicy:
#     automated:
#       prune: false
#     syncOptions:
#     - FailOnSharedResource=false
#   project: k8s-spb2-backend1
#   destination:
#     name: k8s-spb2-backend1
#     namespace: kube-system
#   source:
#       repoURL: 'https://artifactory.playteam.ru:443/artifactory/helm/'
#       targetRevision: v1.11.0
#       chart: cert-manager
#       helm:
#         releaseName: cert-manager
#         valuesObject:
#           #Values
#           image:
#             repository:  registry.playteam.ru/cert-manager/cert-manager-controller
#             tag: v1.11.0-698
#           webhook:
#             image:
#               repository:  registry.playteam.ru/cert-manager/cert-manager-webhook
#               tag: v1.11.0-698
#           cainjector:
#             image:
#               repository: registry.playteam.ru/cert-manager/cert-manager-cainjector
#               tag: v1.11.0-698
#           acmesolver:
#             image:
#               repository: registry.playteam.ru/cert-manager/cert-manager-acmesolver
#               tag: v1.11.0-698
#           startupapicheck:
#             image:
#               repository: registry.playteam.ru/cert-manager/cert-manager-ctl
#               tag: v1.11.0-698
#           tolerations:
#           - key: "node-role.kubernetes.io/infr"
#             operator: "Exists"
#             effect: "NoSchedule"
#           affinity:
#             nodeAffinity:
#               preferredDuringSchedulingIgnoredDuringExecution:
#                 - weight: 1
#                   preference:
#                     matchExpressions:
#                     - key: "node-role.kubernetes.io/infr"
#                       operator: "Exists"
#           webhook:
#             tolerations:
#             - key: "node-role.kubernetes.io/infr"
#               operator: "Exists"
#               effect: "NoSchedule"
#             affinity:
#               nodeAffinity:
#                 preferredDuringSchedulingIgnoredDuringExecution:
#                   - weight: 1
#                     preference:
#                       matchExpressions:
#                       - key: "node-role.kubernetes.io/infr"
#                         operator: "Exists"
#           cainjector:
#             tolerations:
#             - key: "node-role.kubernetes.io/infr"
#               operator: "Exists"
#               effect: "NoSchedule"
#             affinity:
#               nodeAffinity:
#                 preferredDuringSchedulingIgnoredDuringExecution:
#                   - weight: 1
#                     preference:
#                       matchExpressions:
#                       - key: "node-role.kubernetes.io/infr"
#                         operator: "Exists"

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  destination:
    server: https://spoke-1-control-plane:6443
    namespace: cert-manager
  source:
    repoURL: 'https://github.com/nomad-mrkn/charts.git'
    targetRevision: HEAD
    path: cert-manager
    helm:
      values: |
        installCRDs: true