apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-custom-resource
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - FailOnSharedResource=false
  project: k8s-spb2-backend1
  destination:
    name: k8s-spb2-backend1
    namespace: kube-system
  source:
      repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: clusters/demo1/custom-resource
