apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-spb2-backend3
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  description: Project for demo3 cluster
  sourceRepos:
    - https://github.com/nomad-mrkn/*
  destinations:
    - name: kind-spoke-3
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: false
