apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-role
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/type: patchable
rules: []
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jit-rbac-fluent-bit-rules
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
data:
  rules.json: |
    [
      {
        "apiGroups": ["apps"],
        "resources": ["daemonsets", "deployments"],
        "verbs": ["create", "update", "patch", "get", "list", "watch", "delete"]
      },
      {
        "apiGroups": [""],
        "resources": [
          "serviceaccounts",
          "services",
          "configmaps",
          "secrets",
          "pods",
          "pods/log",
          "namespaces",
          "nodes"
        ],
        "verbs": ["create", "update", "patch", "get", "list", "watch", "delete"]
      },
      {
        "apiGroups": ["rbac.authorization.k8s.io"],
        "resources": [
          "clusterroles",
          "clusterrolebindings"
        ],
        "verbs": ["create", "update", "patch", "get", "list", "watch", "delete"]
      },
      {
        "apiGroups": ["batch"],
        "resources": ["jobs"],
        "verbs": ["create", "delete", "list", "get", "watch", "update"]
      }
    ]
