apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-node-feature-discovery
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-node-feature-discovery
rules:
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: [""]
    resources:
      - serviceaccounts
      - services
      - configmaps
      - secrets
      - pods
      - pods/log
      - events
      - endpoints
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch"]
  
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["nfd.k8s-sigs.io"]
    resources:
      - nodefeatures
      - nodefeaturegroups
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["topology.node.k8s.io"]
    resources:
      - noderesourcetopologies
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
      - prometheusrules
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["policy"]
    resources:
      - podsecuritypolicies
      - poddisruptionbudgets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["autoscaling.k8s.io"]
    resources:
      - horizontalpodautoscalers
      - verticalpodautoscalers
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["create", "delete", "list", "get", "watch", "update", "patch"]