apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-policy-reporter
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-policy-reporter
rules:
  - apiGroups: [""]
    resources:
      - serviceaccounts
      - services
      - configmaps
      - secrets
      - pods
      - events
      - endpoints
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

