apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-velero
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-velero
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "update", "patch", "get", "list", "watch"]

  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: [""]
    resources:
      - serviceaccounts
      - services
      - configmaps
      - secrets
      - pods
      - pods/log
      - events
      - endpoints
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["create", "delete", "list", "get", "watch", "update"]

  # VictoriaMetrics ServiceScrape for metrics
  - apiGroups: ["operator.victoriametrics.com"]
    resources: ["vmservicescrapes"]
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  # Vault Secrets Operator CRs if used for credentials
  - apiGroups: ["ricoberger.de"]
    resources: ["vaultsecrets"]
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  # Velero CRDs
  - apiGroups: ["velero.io"]
    resources:
      - backups
      - restores
      - backupstoragelocations
      - volumesnapshotlocations
      - schedules
      - downloadrequests
      - deletebackuprequests
      - podvolumebackups
      - podvolumerestores
      - serverstatusrequests
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
