apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-certmanager
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac-roles
    jit-rbac/app-type: certmanager
rules:
  # Core Kubernetes resources for cert-manager
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - events
      - namespaces
      - pods
      - secrets
      - serviceaccounts
      - services
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # cert-manager specific resources
  - apiGroups: ["cert-manager.io"]
    resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["cert-manager.io"]
    resources:
      - certificates/status
      - certificaterequests/status
      - issuers/status
      - clusterissuers/status
      - certificates/finalizers
      - certificaterequests/finalizers
    verbs: ["update", "patch"]
  
  # ACME specific resources
  - apiGroups: ["acme.cert-manager.io"]
    resources:
      - orders
      - challenges
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["acme.cert-manager.io"]
    resources:
      - orders/status
      - orders/finalizers
      - challenges/status
      - challenges/finalizers
    verbs: ["update", "patch"]
  
  # Webhook and CRD management
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # Deployment and service management
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # RBAC for cert-manager components
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # Gateway API support (optional)
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gateways
      - httproutes
    verbs: ["get", "list", "watch", "update", "patch"]
  
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gateways/finalizers
      - httproutes/finalizers
    verbs: ["update", "patch"]
  
  # Ingress support
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch", "update", "patch"]
  
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses/finalizers
    verbs: ["update", "patch"]
  
  # Coordination for leader election
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["create", "update", "patch", "get", "list", "watch"]
  
  # Certificate signing
  - apiGroups: ["certificates.k8s.io"]
    resources:
      - certificatesigningrequests
    verbs: ["get", "list", "watch", "update", "patch"]
  
  - apiGroups: ["certificates.k8s.io"]
    resources:
      - certificatesigningrequests/status
    verbs: ["update", "patch"]
  
  - apiGroups: ["certificates.k8s.io"]
    resources:
      - signers
    verbs: ["sign"]
  
  # Service account token creation
  - apiGroups: [""]
    resources:
      - serviceaccounts/token
    verbs: ["create"]
  
  # Events and logging
  - apiGroups: [""]
    resources:
      - events
    verbs: ["create", "patch", "get", "update", "list", "watch"]
  
  # Authorization checks
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - subjectaccessreviews
    verbs: ["create"]
