apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac-roles
    jit-rbac/app-type: prometheus
rules:
  # Core Kubernetes resources for monitoring
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - events
      - namespaces
      - nodes
      - nodes/metrics
      - pods
      - secrets
      - serviceaccounts
      - services
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # Prometheus Operator CRDs
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - alertmanagers
      - alertmanagerconfigs
      - prometheuses
      - prometheusrules
      - servicemonitors
      - podmonitors
      - probes
      - thanosrulers
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # VictoriaMetrics Operator CRDs (if used)
  - apiGroups: ["operator.victoriametrics.com"]
    resources:
      - vmagents
      - vmalerts
      - vmauths
      - vmclusters
      - vmnodescrapes
      - vmpodscrapes
      - vmrules
      - vmservicescrapes
      - vmsingles
      - vmstaticscrapes
      - vmusers
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # Grafana CRDs
  - apiGroups: ["grafana.integreatly.org"]
    resources:
      - grafanas
      - grafanadashboards
      - grafanadatasources
      - grafanafolders
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # Deployments and StatefulSets for monitoring components
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # RBAC for monitoring components
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # Network policies for monitoring
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # Storage for persistent volumes
  - apiGroups: [""]
    resources:
      - persistentvolumes
      - persistentvolumeclaims
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs: ["get", "list", "watch"]
  
  # Pod security policies (if used)
  - apiGroups: ["policy"]
    resources:
      - podsecuritypolicies
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete", "use"]
  
  # Pod disruption budgets
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # Horizontal Pod Autoscaler
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # Custom Resource Definitions
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # Admission controllers
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # Service account token creation
  - apiGroups: [""]
    resources:
      - serviceaccounts/token
    verbs: ["create"]
  
  # Events and logging
  - apiGroups: [""]
    resources:
      - events
    verbs: ["create", "patch", "get", "update", "list", "watch"]
  
  # Authorization checks
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - subjectaccessreviews
    verbs: ["create"]
  
  # Coordination for leader election
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["create", "update", "patch", "get", "list", "watch"]
