apiVersion: batch/v1
kind: CronJob
metadata:
  name: argocd-jit-rbac-cleanup-cron
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac-cron
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 900
      template:
        metadata:
          labels:
            app.kubernetes.io/part-of: argo-jit-rbac-cron
        spec:
          serviceAccountName: argocd-manager
          restartPolicy: Never
          containers:
          - name: cleanup
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args:
              - |
                echo "=== JIT RBAC Cleanup Cron Job ===";
                echo "Starting cleanup at $(date)";
                
                echo "Checking for temporary ClusterRoleBindings...";
                CRBS=$(kubectl get clusterrolebinding -l app.kubernetes.io/part-of=argo-jit-rbac -o name 2>/dev/null || echo "");
                if [ -n "$CRBS" ]; then
                  echo "Found temporary CRBs:";
                  echo "$CRBS";
                  kubectl delete clusterrolebinding -l app.kubernetes.io/part-of=argo-jit-rbac --ignore-not-found=true;
                  echo "Deleted temporary CRBs";
                else
                  echo "No temporary CRBs found";
                fi
                
                echo "Checking for JIT ClusterRoles to clear rules...";
                ROLES=$(kubectl get clusterrole -l app.kubernetes.io/part-of=argo-jit-rbac -o name 2>/dev/null | grep -v "argocd-manager-watcher" || echo "");
                if [ -n "$ROLES" ]; then
                  echo "Found JIT ClusterRoles:";
                  echo "$ROLES";
                  for role in $ROLES; do
                    role_name=$(echo "$role" | cut -d'/' -f2);
                    echo "Ensuring empty rules for ClusterRole: $role_name";
                    kubectl patch clusterrole "$role_name" --type=merge -p '{"rules": []}' || echo "Patch failed for $role_name";
                  done
                  echo "Ensured empty rules for all JIT ClusterRoles";
                else
                  echo "No JIT ClusterRoles found";
                fi
                
                echo "Checking for old cleanup pods...";
                kubectl delete pod -n kube-system -l app.kubernetes.io/part-of=argo-jit-rbac --field-selector=status.phase=Succeeded --ignore-not-found=true || true;
                kubectl delete pod -n kube-system -l app.kubernetes.io/part-of=argo-jit-rbac-cron --field-selector=status.phase=Succeeded --ignore-not-found=true || true;
                
                echo "Cleanup completed at $(date)";

