apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend3-fluent-bit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=false
  project: default
  destination:
    name: kind-test-3
    namespace: fluent-bit
  sources:
    - repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: shared/jit-rbac
      kustomize:
        commonLabels:
          jit-rbac/app: k8s-spb2-backend3-fluent-bit
        patches:
          - target:
              kind: ClusterRole
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-fluent-bit
          - target:
              kind: ClusterRoleBinding
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-fluent-bit
              - op: replace
                path: /roleRef/name
                value: argocd-manager-fluent-bit
          - target:
              kind: Job
              name: APP_NAME_PLACEHOLDER-cleanup-old-rbac
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend3-fluent-bit-cleanup-old-rbac
          - target:
              kind: Job
              name: APP_NAME_PLACEHOLDER-cleanup
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend3-fluent-bit-cleanup
    - repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
      targetRevision: HEAD
      path: shared/jit-rbac-roles
      directory:
        include: fluent-bit-role.yaml
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: fluent-bit
      helm:
        releaseName: k8s-spb2-backend3-fluent-bit
        values: |
          kind: DaemonSet