apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend3-jit-rbac-cleanup-cron
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=false
  project: default
  destination:
    name: kind-test-3
    namespace: kube-system
  source:
    repoURL: 'https://github.com/nomad-mrkn/zargocd.git'
    targetRevision: HEAD
    path: clusters/test2/custom-resource
    directory:
      include: cleanup-cronjob.yaml