# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: argocd-manager-certmanager
#   annotations:
#     argocd.argoproj.io/sync-wave: "-2"
#   labels:
#     app.kubernetes.io/part-of: argo-jit-rbac
# rules:
#   - apiGroups: ["admissionregistration.k8s.io", "apiextensions.k8s.io", "apiregistration.k8s.io", "apps", "autoscaling.k8s.io", "autoscaling", "batch", "cert-manager.io", "extensions", "flowcontrol.apiserver.k8s.io", "grafana.integreatly.org", "jaegertracing.io", "keda.sh", "monitoring.coreos.com", "networking.k8s.io", "operator.victoriametrics.com", "policy", "rbac.authorization.k8s.io", "ricoberger.de", "", "velero.io"]
#     resources:
#       - mutatingwebhookconfigurations
#       - validatingwebhookconfigurations
#       - customresourcedefinitions
#       - apiservices
#       - daemonsets
#       - deployments
#       - statefulsets
#       - verticalpodautoscalers
#       - horizontalpodautoscalers
#       - cronjobs
#       - jobs
#       - certificates
#       - certificaterequests
#       - issuers
#       - ingresses
#       - flowschemas
#       - prioritylevelconfigurations
#       - grafanadashboards
#       - jaegers
#       - scaledobjects
#       - podmonitors
#       - prometheusrules
#       - servicemonitors
#       - ingressclasses
#       - networkpolicies
#       - vmagents
#       - vmnodescrapes
#       - vmpodscrapes
#       - vmservicescrapes
#       - poddisruptionbudgets
#       - podsecuritypolicies
#       - clusterrolebindings
#       - clusterroles
#       - rolebindings
#       - roles
#       - vaultsecrets
#       - configmaps
#       - endpoints
#       - namespaces
#       - pods
#       - secrets
#       - serviceaccounts
#       - services
#       - backupstoragelocations
#       - schedules
#       - volumesnapshotlocations
#     verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
#   - apiGroups: ["argoproj.io"]
#     resources: ["applications"]
#     verbs: ["get", "list", "watch"]
#   - apiGroups: ["authorization.k8s.io"]
#     resources: ["subjectaccessreviews"]
#     verbs: ["create"]
#   - apiGroups: [""]
#     resources: ["events"]
#     verbs: ["create", "patch", "get", "update", "list", "watch"]
#   - apiGroups: [""]
#     resources: ["serviceaccounts/token"]
#     verbs: ["create"]
#   - apiGroups: ["certificates.k8s.io"]
#     resources: ["certificatesigningrequests", "certificatesigningrequests/status"]
#     verbs: ["get", "list", "watch", "update", "patch"]
#   - apiGroups: ["certificates.k8s.io"]
#     resources: ["signers"]
#     verbs: ["sign"]
#   - apiGroups: ["cert-manager.io"]
#     resources: ["signers"]
#     verbs: ["approve"]
#   - apiGroups: ["cert-manager.io"]
#     resources: ["certificaterequests/status", "certificaterequests/finalizers", "certificates/status", "certificates/finalizers"]
#     verbs: ["update", "patch"]
#   - apiGroups: ["cert-manager.io"]
#     resources: ["clusterissuers", "issuers"]
#     verbs: ["get", "list", "watch", "update", "patch"]
#   - apiGroups: ["cert-manager.io"]
#     resources: ["clusterissuers/status", "issuers/status"]
#     verbs: ["update", "patch"]
#   - apiGroups: ["acme.cert-manager.io"]
#     resources: ["orders", "orders/status", "orders/finalizers", "challenges", "challenges/status", "challenges/finalizers"]
#     verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
#   - apiGroups: ["gateway.networking.k8s.io"]
#     resources: ["gateways", "gateways/finalizers", "httproutes", "httproutes/finalizers"]
#     verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
#   - apiGroups: ["coordination.k8s.io"]
#     resources: ["leases"]
#     verbs: ["get", "update", "patch", "create", "list", "watch"]
#   - apiGroups: ["networking.k8s.io"]
#     resources: ["ingresses/finalizers"]
#     verbs: ["update", "patch"]
#   - apiGroups: ["route.openshift.io"]
#     resources: ["routes/custom-host"]
#     verbs: ["create"]
#   - apiGroups: [""]
#     resources: ["pods/log"]
#     verbs: ["get", "list", "watch"]
#   - apiGroups: ["rbac.authorization.k8s.io"]
#     resources: ["clusterroles"]
#     verbs: ["bind", "escalate", "get", "list", "watch"]
#   - apiGroups: ["rbac.authorization.k8s.io"]
#     resources: ["roles"]
#     verbs: ["bind", "escalate", "get", "list", "watch"]

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-certmanager
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac-roles
    jit-rbac/app-type: certmanager
rules:
  # Core Kubernetes resources for cert-manager
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - events
      - namespaces
      - pods
      - secrets
      - serviceaccounts
      - services
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # cert-manager specific resources
  - apiGroups: ["cert-manager.io"]
    resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["cert-manager.io"]
    resources:
      - certificates/status
      - certificaterequests/status
      - issuers/status
      - clusterissuers/status
      - certificates/finalizers
      - certificaterequests/finalizers
    verbs: ["update", "patch"]
  
  # ACME specific resources
  - apiGroups: ["acme.cert-manager.io"]
    resources:
      - orders
      - challenges
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["acme.cert-manager.io"]
    resources:
      - orders/status
      - orders/finalizers
      - challenges/status
      - challenges/finalizers
    verbs: ["update", "patch"]
  
  # Webhook and CRD management
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # Deployment and service management
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # RBAC for cert-manager components
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  # Gateway API support (optional)
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gateways
      - httproutes
    verbs: ["get", "list", "watch", "update", "patch"]
  
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gateways/finalizers
      - httproutes/finalizers
    verbs: ["update", "patch"]
  
  # Ingress support
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch", "update", "patch"]
  
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses/finalizers
    verbs: ["update", "patch"]
  
  # Coordination for leader election
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["create", "update", "patch", "get", "list", "watch"]
  
  # Certificate signing
  - apiGroups: ["certificates.k8s.io"]
    resources:
      - certificatesigningrequests
    verbs: ["get", "list", "watch", "update", "patch"]
  
  - apiGroups: ["certificates.k8s.io"]
    resources:
      - certificatesigningrequests/status
    verbs: ["update", "patch"]
  
  - apiGroups: ["certificates.k8s.io"]
    resources:
      - signers
    verbs: ["sign"]
  
  # Service account token creation
  - apiGroups: [""]
    resources:
      - serviceaccounts/token
    verbs: ["create"]
  
  # Events and logging
  - apiGroups: [""]
    resources:
      - events
    verbs: ["create", "patch", "get", "update", "list", "watch"]
  
  # Authorization checks
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - subjectaccessreviews
    verbs: ["create"]