apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-full
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookFailed
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
rules:
  - apiGroups: ["admissionregistration.k8s.io", "apiextensions.k8s.io", "apiregistration.k8s.io", "apps", "autoscaling.k8s.io", "autoscaling", "batch", "cert-manager.io", "extensions", "flowcontrol.apiserver.k8s.io", "grafana.integreatly.org", "jaegertracing.io", "keda.sh", "monitoring.coreos.com", "networking.k8s.io", "operator.victoriametrics.com", "policy", "rbac.authorization.k8s.io", "ricoberger.de", "", "velero.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
      - customresourcedefinitions
      - apiservices
      - daemonsets
      - deployments
      - statefulsets
      - verticalpodautoscalers
      - horizontalpodautoscalers
      - cronjobs
      - jobs
      - certificates
      - certificaterequests
      - issuers
      - ingresses
      - flowschemas
      - prioritylevelconfigurations
      - grafanadashboards
      - jaegers
      - scaledobjects
      - podmonitors
      - prometheusrules
      - servicemonitors
      - ingressclasses
      - networkpolicies
      - vmagents
      - vmnodescrapes
      - vmpodscrapes
      - vmservicescrapes
      - poddisruptionbudgets
      - podsecuritypolicies
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
      - vaultsecrets
      - configmaps
      - endpoints
      - namespaces
      - pods
      - secrets
      - serviceaccounts
      - services
      - backupstoragelocations
      - schedules
      - volumesnapshotlocations
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]