apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  generateName: full-install-  
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed,HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-manager-full
subjects:
- kind: ServiceAccount
  name: argocd-manager
  namespace: kube-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend2-certmanager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - CreateNamespace=true
  project: default
  destination:
    server: https://spoke-2-control-plane:6443
    namespace: cert-manager
  source:
    repoURL: 'https://github.com/nomad-mrkn/charts.git'
    targetRevision: HEAD
    path: cert-manager
    helm:
      values: |
        installCRDs: true