---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ldap-monitoring-group
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: lnxMonitoringTeam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-group
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ldap-devops-clusteradmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: lnxAdmins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ldap-CS_k8s_prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: CS_k8s_prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ldap-Kubernetes_RBAC_Audit_CS_prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: Kubernetes_RBAC_Audit_CS_prod
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: Kubernetes_RBAC_Audit_CS_prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-manager-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-manager-watcher
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system